### ISSUE TITLE
Serialization exception swallowed when `NatsPubOpts.WaitUntilSent = false`

### ISSUE THREAD

**Issue by jasper-d** [nats-io/nats.net.v2#138]
### What version were you using?

nats-server: v2.9.20
Client: 50f22214daaf16c3f6ef34967507326293f143c2

### What environment was the server running in?

Fedora Linux 6.5.5-200.fc38.x86_64 #&#x2060;1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 unknown unknown GNU/Linux

### Is this defect reproducible?

Yes, see failing tests in https://github.com/nats-io/nats.net.v2/pull/136. When using `WaitUntilSent = false`, an `OperationCancelledException` is observed. When using `WaitUntilSent = true`, an `InvalidOperationException` is observed.

### Given the capability you are leveraging, describe your expectation?

Serialization exceptions should be thrown when calling `PublishAsync<T>` with `NatsPubOpts.WaitUntilSent = false`.

### Given the expectation, what is the defect you are observing?

Serialization exceptions are not observable.

**Comment by mtmk** [comment]
I can repro the issue.
