### ISSUE TITLE
Remove JetStream consume / fetch default batch

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#240]
### Proposed change

Overload + config ctor:
```
consume/fetch(int batch)
consume/fetch(new Config(int batch))
```

This would eliminate errors like setting consumer batch size less than 1000 then having issues consuming.

**Comment by Jarema** [comment]
I think that consume should have built in default batch value (but configurable). For `fetch` I agree that there should be no default value.

**Comment by mtmk** [comment]
> I think that consume should have built in default batch value (but configurable).

what would be a sensible default? Currently it's 1000
