### ISSUE TITLE
Unhandled protocol message: 409 Server Shutdown

### ISSUE THREAD

**Issue by robertmircea** [nats-io/nats.net.v2#264]
### Proposed change

Handle server shutdown notification. Whenever I shutdown (gracefully) the server, NATS logs the following message:

```[06:21:26.998 WARN  NATS.Client.JetStream.Internal.NatsJSConsume] Unhandled protocol message: 409 Server Shutdown```

This type of notification from server can be useful for graceful consumer shutdown.

### Use case

Clean shutdown of the consumers

**Comment by mtmk** [comment]
@robertmircea merge closed the issue automatically. Feel free to reopen.

Server shutting down is considered a recoverable error so consumer will keep trying to connect. With #265 to shutdown the consumer now we can use notifications:

https://github.com/nats-io/nats.net.v2/blob/87b897bd9068d698a4adb64eb947cc26ecc2ee55/tests/NATS.Client.JetStream.Tests/ConsumerNotificationTest.cs#L28-L33
