### ISSUE TITLE
Support Keyed DI services in .NET 8

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats.net.v2#315]
A user may want to configure multiple `INatsConnection` in DI, and .NET 8 allows for specifying [Keyed DI Services](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#keyed-di-services)

Add optional param to take key for `.AddNats`

**Comment by rickdotnet** [comment]
I took an initial stab at this [here](https://github.com/nats-io/nats.net.v2/commit/550470425ba49602f6997f6f121be8063e9753a1).  I don't have a proper setup to run the test suite, but it did pass my pseudo-test via console app.

**Comment by mtmk** [comment]
That looks good @rickdotnet please feel free open a PR 💯 

> I don't have a proper setup to run the test suite

fyi, you only need a `nats-server.exe` in your `PATH`. All of the tests would run in isolation.
