### ISSUE TITLE
JWT Auth Handling Port

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.net.v2#35]

**Comment by Jarema** [comment]
@scottf did you mean auth with JWT/creds, or having the JWT management API?

**Comment by scottf** [comment]
> @scottf did you mean auth with JWT/creds, or having the JWT management API?

Auth Handling via JWT credentials. Maybe also any JWT utils from Java as the JWT utils don't exist in .net v1

**Comment by Jarema** [comment]
Yes.
You also need to sign the nonce from the server INFO with the private key.

**Comment by mtmk** [comment]
> Yes. You also need to sign the nonce from the server INFO with the private key. It has to be also handled on reconnections.

nice. yes those are done as well. In that case I'm going to close this issue. We can open another for JWT utils later since I think that should be a separate thing.
