### ISSUE TITLE
Expose headers on NatsSvcMsg

### ISSUE THREAD

**Issue by niklasfp** [nats-io/nats.net.v2#370]
### Proposed change

Hi Guys,

I was working on some nats service code, and got stuck when I found out the headers on the NatsSvcMsg is not exposed

Is there a deeper reason to why the headers on [NatsSvcMsg Object](https://github.com/nats-io/nats.net.v2/blob/main/src/NATS.Client.Services/NatsSvcMsg.cs) is not exposed from the underlying NatsMsg ?

### Use case

Use headers on service requests :smile

### Contribution

If it's ok to expose the headers, and it's just a matter of forwarding them from the NatsMsg, then sure, I can do a pr 👍

**Comment by mtmk** [comment]
Oversight on my part. Yes, please go for it! 💯
