### ISSUE TITLE
Update NATS.Client.Hosting package as NATS.Extensions.Microsoft.DependencyInjection

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#392]
### Proposed change

Update NATS.Client.Hosting package as NATS.Extensions.Microsoft.DependencyInjection and mark NATS.Client.Hosting obsolete.

### Use case

Confusing for new users on NuGet search results. Also x.Extensions.Microsoft.DependencyInjection seems to be the convention.

cc @mrpmorris thanks for the suggestion

**Comment by rickdotnet** [comment]
I took an initial stab at this [here](https://github.com/rickdotnet/nats.net.v2/blob/feature/392-417-di-builder/src/NATS.Extensions.Microsoft.DependencyInjection/NatsHostingExtensions.cs).

**Comment by mtmk** [comment]
thanks @rickdotnet 🥇 really appreciate the contributions!

**Comment by mtmk** [comment]
> I took an initial stab at this [here](https://github.com/nats-io/nats.net.v2/commit/3a47c271b058c662ac96eb8d3be1475f036ee656).

@rickdotnet, I dropped a few comments but realized it's not a PR. Please feel free to create one and ref both issues if you like 💯

**Comment by rickdotnet** [comment]
Sure, will clean it up and put something out soon.

**Comment by mrpmorris** [comment]
Nice 🙂
