### ISSUE TITLE
INatsJSContextFactory should be public?

### ISSUE THREAD

**Issue by sgwong** [nats-io/nats.net.v2#409]
### Observed behavior

currently the INatsJSContextFactory is define as internal which prevent it to use externally (or this plan for internal interface only?):

`internal interface INatsJSContextFactory`

the NatsJSContextFactory define as public. I think the `INatsJSContextFactory` should be public

Not sure anyone use the INatsJSContextFactory? or can remove it?

### Expected behavior

`INatsJSContextFactory` should be public

### Server and client version

nats.net 2.1.1

**Comment by mtmk** [comment]
I missed that one! thanks for reporting 💯
