### ISSUE TITLE
Simplify JSON serialization setup

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#417]
### Proposed change

Currently because we're AOT compatible context or ad-hoc JSON serialization requires a bit of setup to register in the connection:

```csharp
var jsonRegistry = new NatsJsonContextSerializerRegistry(MyJsonContext.Default);
return opts with { SerializerRegistry = jsonRegistry };
```

We should be able to simplify this when using hosting extensions.

**Comment by rickdotnet** [comment]
I took an initial stab at this [here](https://github.com/rickdotnet/nats.net.v2/blob/3a47c271b058c662ac96eb8d3be1475f036ee656/tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/NatsHostingExtensionsTests.cs#L51) as part of #392. Let me know if it aligns with what you were thinking and I can tweak it.
