### ISSUE TITLE
JetStream Backoff

### ISSUE THREAD

**Issue by alberk8** [nats-io/nats.net.v2#422]
### Observed behavior

With  code below it looks like the backoff is not in effect.  Also there is no reference anywhere in the [source](https://github.com/nats-io/nats.net.v2/blob/56f831f8e59091aa91be6169aaad835368905c37/src/NATS.Client.JetStream/Models/ConsumerConfig.cs#L227).

### Expected behavior

Backoff Setting works

### Server and client version

Server: v2.10.11
Client: NATS.Client.JetStream v2.1.2

### Host environment

Official NATS docker (latest) with JetStream enabled.

### Steps to reproduce

```
var consumer = await jsContext.CreateOrUpdateConsumerAsync("EVENTS", new ConsumerConfig(consumerName)
{
    DeliverPolicy = ConsumerConfigDeliverPolicy.All,
    FilterSubject = "data.>",
    AckPolicy = ackPolicy,
    AckWait = ackWait,
    
    MaxDeliver = 5,
    Backoff = new List<long>() { (long) TimeSpan.FromSeconds(1).TotalSeconds, (long)TimeSpan.FromSeconds(2).TotalSeconds }
});

 await foreach (NatsJSMsg<Person> msg in consumer.ConsumeAsync<Person>())
 {
     Console.WriteLine($"Subject: {msg.Subject} Size: {msg.Size}");
     var md = msg.Metadata;
     if (md.HasValue)
     {
        Console.WriteLine($"Num Delivered: {md.Value.NumDelivered} TimeStamp: {md.Value.Timestamp.ToLocalTime()}");
        Console.WriteLine($"Consumer Seq: {md.Value.Sequence.Consumer} Stream Seq: {md.Value.Sequence.Stream}");
     }
     await msg.NakAsync();
 }
```

**Comment by mtmk** [comment]
it might be nanoseconds, could you try that?
We changed everything to be TimeSpan but missed this one I think 🤔

**Comment by alberk8** [comment]
I have changed to MicroSeconds and there is no difference.  The Re-Delivery went through in quick succession.

**Comment by mtmk** [comment]
> I have changed to MicroSeconds and there is no difference. The Re-Delivery went through in quick succession.

it's should be nano .. another x1000

> 
> Looking at the source code, it does not seems that Backoff is implemented.

I think this is just passed to the server, I don't think there is anything to implement on client side, is there?

**Comment by alberk8** [comment]
Thanks.   I really missed it.  Nanoseconds did the trick.  It is working as expected.

**Comment by yeongjonglim** [comment]
Hi @mtmk, is there a chance that we might want to change the Backoff property to use the type TimeSpan to better align the other properties and to prevent confusion like this? I don't mind to help out if you don't mind that breaking change.

**Comment by yeongjonglim** [comment]
Hey @mtmk, I have submitted a PR for this change. It will introduce a breaking change, which I'm unsure if it will be okay. Please let me know if you would like to see any adjustments.
