### ISSUE TITLE
Subscriptions dropped shortly after registration

### ISSUE THREAD

**Issue by nicol1993** [nats-io/nats.net.v2#505]
### Observed behavior

Posting this issue as requested by @mtmk in the NATS slack channel.

I am registering some endpoints on my NATS service and I am able to successfully do a Request-Reply on these subscriptions, however my subscription is abruptly dropped from my service shortly after registration.

I have no explicit calls to unsubscribe from these subscriptions. Below is how I have registered my endpoints and I deal with my requests in a scoped lifetime.

```
 public static async Task<IApplicationBuilder> UseNatsSvcServer(this IApplicationBuilder app)
    {
        var natsConnection = app.ApplicationServices.GetRequiredService<MyNatsConnection>();
        var context = new NatsSvcContext(natsConnection);
        
        var reg = app.ApplicationServices.GetRequiredService<NatsServiceEndpointRegistrar>();
        
        var service = await context.AddServiceAsync("my-svc", "1.0.0", "my.queue.group");
        var group = await service.AddGroupAsync("my.nats.group");
        
        // Register endpoints
        await group.AddEndpointAsync(reg.HandleScopedRequest<AreaRequest, AreaEndpoint>,
            nameof(AreaEndpoint), "area.get", "my.queue.group", null, NatsJsonSerializer<AreaRequest>.Default);
        
        return app;
    }
```

I have also noticed I do not have this issue in a different implementation I had using a Singleton approach so scoping appears to be part of the issue.

### Expected behavior

With the setup I have posted, I would expect the subscriptions to continue until `UnsubscribeAsync()` is called or the instance is disposed of.

### Server and client version

Nats-Server: v0.1.4
Nats Cli Client: v0.1.4
NATS.NET v2 2.2.1

### Host environment

Occurs on both NATS Docker Container and Synadia Cloud

### Steps to reproduce

- Register `NatsConnection `class
- Register new service on `NatsSvcContext`
- Register endpoints and handle requests in a Scoped lifetime manner
- Request on subject and get successful reply after a few requests
- Subscription then dropped automatically shortly afterwards.

**Comment by mtmk** [comment]
thanks @nicol1993 for the issue. We have seen similar reports about services dropping the endpoint subscriptions which I believe is caused by subscription weak refs being GCed.

**Comment by heckradr** [comment]
I have a similar problem at the moment, but with the SubscribeCoreAsync method.

Maybe this information will help: If I run the application under Windows (in the debugger), everything works as expected. After deploying it in a Docker container, the problem occurs.

@mtmk  Can I roll back to a previous version as a short-term solution? Which version would be suitable?

**Comment by mtmk** [comment]
@heckradr thanks for the info. I'd imagine GC might behave differently in debug, maybe that's why.

this feature is built in virtually from day zero so you can really roll back. The current suggestion is to place the instance (NatsSub in your case, returned from SubscribeCoreAsync) in a class field of your object that is a singleton or some sort of manager class, so it is always rooted and not GCed. Clear as mud, right? 😅 ... Hit me on Slack, I can try to help with your specific code base if you like.

**Comment by heckradr** [comment]
@mtmk great, thanks for your quick response 😃 

I already had some kind of manager class / subscription info, but so far without a reference to the NatsSub. I added a NatsSub reference and now it's working in docker too 👍
