### ISSUE TITLE
Version number of client library always set to 1.0.0

### ISSUE THREAD

**Issue by darkwatchuk** [nats-io/nats.net.v2#538]
### Observed behavior

When asking the server for client connections, the version of the this library always comes back as 1.0.0, whereas other libraries come back with the correct versions.  E.g.

NATS CLI Version 0.1.4 is go 1.33.1

Also, would it not be better for the language of the library to be reported as .NET rather than C# as per V1 of the library?

Issues with both .NET framework and Core 

### Expected behavior

I'd expect the library version to get reported correctly ideally with .NET as the library name, rather than C#.
e.g. .NET 2.3.0

### Server and client version

.net client 2.3
server 2.10.16

### Host environment

Windows client

**Comment by mtmk** [comment]
'supposed' to get it from the assembly!?

https://github.com/nats-io/nats.net.v2/blob/77666193a35484886ce522ba1a2e51931a4c5ad6/src/NATS.Client.Core/Internal/ClientOpts.cs#L98-L117

**Comment by darkwatchuk** [comment]
I don't think those attributes go on to the type.
If you change to
    var asm = typeof(ClientOpts).Assembly;

Then it does work, however may be choose AssemblyFileVersionAttribute instead or AssemblyInformationalVersionAttribute, otherwise you get a GUID embedded in the version number?

![image](https://github.com/nats-io/nats.net.v2/assets/29970243/639d2c17-c72c-4a3a-8e54-f27ce1183cd0)

**Comment by mtmk** [comment]
thanks @darkwatchuk that sounds like the solution to me 💯
