### ISSUE TITLE
Remove 'internal subscription on same subject' feature

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#59]
This is to remove subscription reference counting and replicating of messages on the same subject rather than subscribing to the subject again going to the server with a new `SID`.

This would also include making sure we don't leak subject objects in case user code not disposing them. We don't want subscription manager to keep a reference to subject objects keeping them alive even though user code abandoned it.

**Comment by to11mtm** [comment]
I'm curious, what were the reasons for removing the reference counting approach? 

Does this result in extra overhead, in cases where we have a number of subscriptions to the same subject on a client? i.e. if a client has 3 subscriptions with different SIDs to the same subject, will the server send three separate messages?

**Comment by mtmk** [comment]
@to11mtm I removed the ref counting because it was used to maintain 'in-memory' subscriptions feature, as far as I understood. The decision for removing this in-memory subscription feature had a few reasons:
(1) NATS protocol is designed to handle multiple subscription to the same subject from the same client connections since they would have different SIDs. This is a very important concept to support variety of different messaging patterns where the subject may convey information other than a destination. JetStream for example takes advantage of this a lot.
(2) I wanted to expose the protocol to the user as low level as possible at the core NATS level since JetStream and other APIs will be built on top
(3) If this functionality is required, it could be implemented by the user of this API or as an extension e.g. relying on the channel of NatSub
(4) Simplification in general
(5) It's not actually *always* saving server resource (i.e. sending a message more than once) without the knowledge of subject semantics. For example if there is a subscription to A.* and A.B messages sent to A.B would be sent twice. - I realise this may not be a good argument against it but just wanted to highlight the fact anyway.

I hope that makes sense.

Was this something you were relying on?

**Comment by caleblloyd** [comment]
A big reason was also supporting Subscription Options.  There are many new options in `NatsSubOpts` - options that configure timeouts, server-tracked UNSUB, and support using different Serializers.

The Inbox Subscription is actually a Mux Subscription now under the covers - which is actually a little different.  It listens on a single wildcard such as `_INBOX.abcd.>` and delivers all of the inbox messages to the proper inboxes.

**Comment by to11mtm** [comment]
I appreciate the background, those definitely all make a lot of sense! Especially for cases like JetStream where you really can't do these sorts of things.

> Was this something you were relying on?

A project I am working with was using AlterNATS, and due to some of the patterns we were using it was pretty helpful for our use case.

All of that said, I certainly agree that it could be done as an extension on `NatsSub` or via some other shim class to track refcounts across the connection. 

Thank you again for the information!
