### ISSUE TITLE
API Review - remove Extension Method ReplyAsync

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats.net.v2#76]
`ReplyAsync` Extension Method  doesn't seem to "fit" well with the rest of the library

- It takes a synchronous callback, I don't know if we want to go down the path of making this a pattern
- It doesn't support any `SubOpts` such as queue groups
- It makes assumptions about sending an empty message if an exception is caught
- It doesn't support streaming or chunked replies

I think that the main `Reply` functionality needed is actually already captured in `NatsMsg`.  I don't think we necessarily need another abstraction over it, and just using a Subscription combined with `msg.ReplyAsync` captures all of the use cases with about the same level of effort.

**Comment by mtmk** [comment]
All good points. Makes sense.
