### ISSUE TITLE
Allow Configuration of the BoundedChannel used for a subscription

### ISSUE THREAD

**Issue by to11mtm** [nats-io/nats.net.v2#94]
#### Use Case:

There may be various cases where the default `BoundedChannelOptions` are not optimal for a given use case; examples include:

1. If one would prefer a larger or smaller buffer of messages (especially in one of the below scenarios)
2. If one would prefer to drop older messages when the buffer is full, or perhaps newer messages, or even the write.

#### Proposed Change:

Adding a `BoundedChannelOptions?` property to `NatsSubOpts`, that may be used instead of the default, would allow for easy 'opt-in' customization of parameters while still allowing easy normal use.

#### Who Benefits From The Change(s)?

Users who wish to have more flexibility in subscription channel definition, especially for the cases exampled above. As a more specific example, consider a case where someone *only* cares about the most recent message on a subscription.

#### Alternative Approaches

Alternatively, we could provide some sort of 'constrained' options instead of asking for a full `BoundedChannelOptions`. The main benefit of doing so, would be that we could avoid users accidentally passing `AllowSynchronusContinuations=true`. Admittedly they could also change the `SingleReader` or `SingleWriter` properties from their expected defaults, but neither of those impact `BoundedChannel` currently.

##### Note:

I already drafted a PR for this, apologies for not filing an issue first.

**Comment by caleblloyd** [comment]
We should probably also expose a way to set a default setting for the connection in `NatsOptions`

`Capacity` and `FullMode` do seem like important options to expose.

I don't think setting `AllowSynchronusContinuations=true` or `SingleWriter=false` would really hurt anything, although `SingleWriter=false` will be the default if not set.

Curious to here @mtmk thoughts also

**Comment by to11mtm** [comment]
> I don't think setting `AllowSynchronusContinuations=true` or `SingleWriter=false` would really hurt anything,

The concern with `AllowSynchronousContinuations=true` is that, based on my understanding of the [remarks on AllowSynchronousContinuations](https://learn.microsoft.com/en-us/dotnet/api/system.threading.channels.channeloptions.allowsynchronouscontinuations?view=net-7.0#remarks), it is possible that a `.ReadAsync()` or `.WaitToReadAsync()` on the channel may be executed on the thread that is writing to the channel, which could(?) cause blocking on the read loop.

**Comment by caleblloyd** [comment]
Maybe we should go ahead and introduce `NatsSubChannelOptions` and limit it to just the fields that we want to support right now - mainly `Capacity` and `FullMode` (and maybe `SingleReader`?)

I can see some edge cases down the road where we might want to support more things - pass in an existing channel, don't close the channel on unsubscribe, etc.

**Comment by mtmk** [comment]
> Maybe we should go ahead and introduce `NatsSubChannelOpts` and limit it to just the fields that we want to support right now - mainly `Capacity` and `FullMode` (and maybe `SingleReader`?)

Sounds good.

> I can see some edge cases down the road where we might want to support more things - pass in an existing channel, don't close the channel on unsubscribe, etc.

This makes a lot of sense. Being able to pass in your own channel and control completion would be very useful.

**Comment by to11mtm** [comment]
> I can see some edge cases down the road where we might want to support more things - pass in an existing channel, don't close the channel on unsubscribe, etc.

As far as as passing in an existing (or just created) channel, I could definitely see cases for that if someone wanted to use something other than BoundedChannel. 

Ref-counted subscription sharing comes to mind, if one wanted to implement that in an extension, it may be better to use an `UnboundedChannel` for the Connection level subscription (vs the individual counted subs, but I digress...)

A Factory (e.x. `Func<Channel<NatsMsg>>? ChannelFactory`) may be the way to go for maximum flexibility, while still allowing for providing a safe default.

> > Maybe we should go ahead and introduce `NatsSubChannelOpts` and limit it to just the fields that we want to support right now - mainly `Capacity` and `FullMode` (and maybe `SingleReader`?)
> 
> Sounds good.

Unless it's worth talking about passing in a channel or channel factory now (which it may be, since it is likely a breaking change compared to the options or would cause confusion in the `NatsSubOpts` API), I can update my PR using a `NatsSubChannelOpts`.

**Comment by mtmk** [comment]
> A Factory (e.x. `Func<Channel<NatsMsg>>? ChannelFactory`) may be the way to go for maximum flexibility, while still allowing for providing a safe default.

What would be the advantage of a factory rather than just passing a channel?

**Comment by to11mtm** [comment]
> What would be the advantage of a factory rather than just passing a channel?

The main potential advantage would be that one could reuse a single `NatsSubOpts` for a series of subscriptions, rather than having to create a new one for every subscription, which can make some composition easier.

**Comment by mtmk** [comment]
NatsSubOpts are struct at the moment.

**Comment by to11mtm** [comment]
> NatsSubOpts are struct at the moment.

Right... but if one pre-set the Channel (in the non-factory case) that channel instance would still get copied...

```
//Alternatively, could get set as a readonly in some other wrapper/etc.
private static readonly NatsSubOpts options = new NatsSubOpts()
{
    //Other desired options set as well,
    ChannelFactory = static () => Channel.CreateUnbounded<NatsMsg>(),
};

public async Task<NatsSub> CreateSub(string subject)
{
    INatsConnection nc;
    return await nc.SubscribeAsync(subject, options);
}
```

Versus if, the channel had to be passed in every time,

```
private static readonly NatsSubOpts? options = new NatsSubOpts()
{
    //Other Opts set here
};

public async Task<NatsSub> CreateSub(string subject)
{
    INatsConnection nc;
    return await nc.SubscribeAsync(subject, options with {Channel = Channel.CreateUnbounded<NatsMsg>()});
}
```

To some extent it boils down to composition preference, but the factory seems less likely to accidentally re-use a pre-set channel for multiple subscriptions...

**Comment by mtmk** [comment]
I'm probably not fully appreciating the benefits of a channel factory. In general, my instinct is to keep `NatsSubOpts` immutable in some fashion. I am leaning towards accepting an optional `Channel<TWrite, TRead>` rather than passing in Bounded channel options. That gives us the best flexibility since users can even implement their own channel readers and writers. If we can agree on that (I think we do at this point?) then we can discuss weather we pass in a factory or simply nullable channel in opts so that we can create a channel optionally in `NatsSub.ctor` e.g. `_channel = opts?.channel ?? Channel.Create...`. I'd love to hear @caleblloyd's opinion as well.

**Comment by mtmk** [comment]
re GC: We should try it, but I think in the first case `myNewChan` would keep `NatsSub` objects alive. Of course you'd lose the ability to unsubscribe in a more controlled manner.

Second case, we might not need `CompletedAsync`:
```csharp
var myNewChan = Channel.CreateUnbounded<int>();
await using var sub1 = await nats.SubscribeAsync<int>("foo", new NatsSubOpts { MaxMsgs = 1 }, channel: myNewChan);
await using var sub2 = await nats.SubscribeAsync<int>("bar", new NatsSubOpts { MaxMsgs = 2 }, channel: myNewChan);
// await consume myNewChan

// sub1 and sub2 will need to be told not to do completion
// otherwise sub1 & 2 would race to complete the channel

// sub1.Unsubscribe/Dispose etc.
```

But regardless, it will complicate things a bit more. Subscriptions will need to be told not to complete the channel. 

So, whether to pass a channel, channel options or only the safe parameters: Passing in a channel wasn't the original intent of this issue, maybe we can drop that. There is already a solution if a user wants to merge messages into a single channel by creating an extra one...

(just saw @to11mtm's comment, sounds like we might be coming to the same conclusion)

**Comment by caleblloyd** [comment]
> re GC: We should try it, but I think in the first case `myNewChan` would keep `NatsSub` objects alive. Of course you'd lose the ability to unsubscribe in a more controlled manner.

Hmm, I would not expect `myNewChan` to keep the `NatsSub` alive, there is no back-reference to the `NatsSub`.  We could test it though

**Comment by mtmk** [comment]
> > re GC: We should try it, but I think in the first case `myNewChan` would keep `NatsSub` objects alive. Of course you'd lose the ability to unsubscribe in a more controlled manner.
> 
> Hmm, I would not expect `myNewChan` to keep the `NatsSub` alive, there is no back-reference to the `NatsSub`. We could test it though

Ah! You're right.

**Comment by to11mtm** [comment]
Updated PR since it sounds like there is general consensus to just add the two specific options for now.
