### ISSUE TITLE
When to return on PublishAsync?

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats.net.v2#99]
Comparing `nats.go` - it uses a [separate Goroutine to run a flusher](https://github.com/nats-io/nats.go/blob/3e4bc5a4f8598ddc50af2d394c2878ae6557fbf0/nats.go#L3308) that is similar to the separate Write Loop that we are using.

When they [write buffers](https://github.com/nats-io/nats.go/blob/3e4bc5a4f8598ddc50af2d394c2878ae6557fbf0/nats.go#L1798), the order appears to be:

1. if the Connection is in a Connecting/Reconnecting state, these buffers get sent to "pending" buffers and saved for later - up to 8MiB (configurable)
2. if the Connection is connected, these buffers get sent to the "active" buffer
3. if the "active" buffer is over 32KiB, flush is called synchronously
4. otherwise a background flusher picks things up

This library is structured slightly differently - there is a `CommandChannel` to enqueue requested commands, which may be batched into write operations.

Right now `PublishAsync` task is completing when the Value has been written to the socket.  This means that many small `await PublishAsync` commands called in a loop will have no opportunity to be batched.

To more closely match the performance of `nats.go`, we could change the default behavior of `PublishAsync` to return after commands have been written to the `CommandChannel`

**Pros:**

- Better performance batching writes for small messages awaited in loop
- Reconnect logic would more closely match `nats.go`

**Considerations:**

- May need Async Error Handler to deal with errors between enqueuing in `CommandChannel` and writing out to Socket
- May need to consider a default `PublishAsync` timeout when Command Channel is full.  Otherwise a full `CommandChannel` while a connection is `Reconnecting` for a long period time will manifest as the application hanging

**Comment by caleblloyd** [comment]
One idea is adding an option to `NatsPubOpts` to control when it will return:

```
/// When set to true, calls to PublishAsync will complete after data has been written to socket
/// Default value is false, and calls to PublishAsync will complete after the publish command has been written to the Command Channel
bool? WaitUntilSent
```

**Comment by mtmk** [comment]
> **Considerations:**
> 
> * May need Async Error Handler to deal with errors between enqueuing in `CommandChannel` and writing out to Socket

We need to review this. Currently for example serialization errors aren't propagated I don't think, which is quite important. This is a problem in general with publishing not specific to this implementation proposal.

> * May need to consider a default `PublishAsync` timeout when Command Channel is full.  Otherwise a full `CommandChannel` while a connection is `Reconnecting` for a long period time will manifest as the application hanging

This is a very good point. With a bounded channel at least we won't fill the memory forever and wait, which is a better option then potentially exiting with OOM exception. But it would be nice to have a way of signaling user code that the buffer is full and we are blocked. Timeout is probably the best way of doing this?
